import { type GetServerSideProps, type NextPage } from 'next'
import Head from 'next/head'
import { signIn } from 'next-auth/react'
import { getServerAuthSession } from '~/server/auth'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Task APP</title>
        <meta
          name='description'
          content='Generated by create-t3-app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center gap-4 bg-neutral-100'>
        <h1 className='text-7xl font-semibold -tracking-widest'>TASK APP</h1>
        <button
          className='rounded-md bg-neutral-900 px-10 py-3 text-2xl font-semibold text-white transition-opacity hover:opacity-80'
          onClick={() => void signIn()}
        >
          SIGN IN
        </button>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ctx => {
  const session = await getServerAuthSession(ctx)

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    redirect: {
      destination: '/dashboard',
      permanent: true,
    },
  }
}
export default Home
